version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: CipherGlider
      POSTGRES_PASSWORD: 1904
      POSTGRES_DB: ProtoCom
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data: 
